### ISSUE TITLE
User visits app

### ISSUE THREAD

**Issue by biglovisa** [adamcaron/tidy_up#1]
As a user, 
when I visit "/tidy-up.herokuapp.com", 
I view a list of tasks, 
a button to log in,
a button to sign up.

**Comment by adamcaron** [comment]
### Problem with 'Sign Up'

The app should **not** allow just anybody to register as an admin. There must be some level of approval for a new admin to be created. 

If anyone can request to become an admin, they must be verified/confirmed by another admin. Perhaps an admin receives an email when someone else requests to become an admin. This seem complicated.

### Proposed Solution

For now, only current admins can add new admins. Remove the 'Sign up' link from the homepage for now.

**Comment by biglovisa** [comment]
This sounds good, maybe we should try to do omniauth with Slack and restrict certain areas of the app to Daisha?

**Comment by adamcaron** [comment]
Omniauth with Slack sounds good. That way people can login and be accountable for their tasks but it will be easy, since they won't need to create a new account. Also, we can automagically reward posse points to people for their task completion.
